# Generated by Django 5.2.3 on 2025-08-07 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaintcategory',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
