# Generated by Django 5.2.4 on 2025-08-07 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0003_alter_community_members_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('complaint_created', 'Complaint Created'), ('notice_created', 'Notice Created'), ('event_created', 'Event Created'), ('poll_created', 'Poll Created'), ('membership_changed', 'Membership Changed'), ('community_created', 'Community Created'), ('community_updated', 'Community Updated'), ('community_deleted', 'Community Deleted')], max_length=32)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('community', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='communities.community')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='communities.userprofile')),
            ],
        ),
    ]
